export enum ACCOUNT_TYPE{
    STUDENT= 'STUDENT',
    EMPLOYER='EMPLOYER'
}

export enum ACCOUNT_STATUS{
    ACTIVE='ACTIVE',
    INACTIVE='INACTIVE',
    BLOCKED='BLOCKED',
    DELETE='DELETE',
    APPROVAL_PENDING='APPROVAL_PANDING'
}